### ISSUE TITLE
import errors while executing

### ISSUE THREAD

**Issue by Saraphie** [eclair4151/SmartCrypto#1]
I'm executing `smartcrypto.py` with `sudo ./smartcrypto.py` and I'm getting the following errors

```
from: can't read /var/mail/__future__
from: can't read /var/mail/PySmartCrypto
./smartcrypto.py: 3: ./smartcrypto.py: import: not found
./smartcrypto.py: 4: ./smartcrypto.py: import: not found
from: can't read /var/mail/PySmartCrypto.command_encryption
./smartcrypto.py: 6: ./smartcrypto.py: import: not found
./smartcrypto.py: 7: ./smartcrypto.py: import: not found
./smartcrypto.py: 8: ./smartcrypto.py: import: not found
./smartcrypto.py: 12: ./smartcrypto.py: UserId: not found
./smartcrypto.py: 13: ./smartcrypto.py: AppId: not found
./smartcrypto.py: 14: ./smartcrypto.py: deviceId: not found
./smartcrypto.py: 15: ./smartcrypto.py: tvIP: not found
./smartcrypto.py: 16: ./smartcrypto.py: tvPort: not found
./smartcrypto.py: 18: ./smartcrypto.py: lastRequestId: not found
./smartcrypto.py: 19: ./smartcrypto.py: Syntax error: "(" unexpected
```

**Comment by eclair4151** [comment]
you have to run it using python not bash. 

try 
python3 smartcrypto.py

**Comment by Saraphie** [comment]
Of course, it seems it getting late, but still an error

```
Traceback (most recent call last):
  File "smartcrypto.py", line 2, in <module>
    from PySmartCrypto import crypto
ImportError: No module named 'PySmartCrypto'
```

**Comment by eclair4151** [comment]
hmm thats odd.

 try to cd out 1 directory and run python3 PySmartCrypto/smartcrypto.py

**Comment by Saraphie** [comment]
shows the same issue

Done for today, wil be back tomorrow on this topic

**Comment by mfl76** [comment]
Same issue on my side. Any idea?

**Comment by eclair4151** [comment]
just made a commit. try to git pull and try again

**Comment by mfl76** [comment]
Thx, now it works to display PIN and enter it. Then following message:
```
Please enter pin from tv: 4308
Got pin: '4308'

AES key: 4d5171fcc48afca06a9718595d2798ef
Traceback (most recent call last):
  File "smartcrypto.py", line 126, in <module>
    output = HelloExchange(tvPIN)
  File "smartcrypto.py", line 55, in HelloExchange
    hello_output = crypto.generateServerHello(UserId,pin)
  File "/home/pi/SmartCrypto/PySmartCrypto/crypto.py", line 39, in generateServerHello
    cipher = AES.new(aes_key, AES.MODE_CBC, iv)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/_mode_cbc.py", line 293, in _create_cbc_cipher
    return CbcMode(cipher_state, iv)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Cipher/_mode_cbc.py", line 97, in __init__
    c_uint8_ptr(iv),
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Util/_raw_api.py", line 144, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
```

**Comment by eclair4151** [comment]
whoops forgot to fix that. try now

**Comment by mfl76** [comment]
Cool, now it works. Thank you very much.
