### ISSUE TITLE
String vs byte_string issue

### ISSUE THREAD

**Issue by luca-angemi** [eclair4151/SmartCrypto#2]
Hi,

after I run 
```bash
python smartcrypto.py
```
I got the same issue after I input then PIN back

```bash
Current state: stopped
Pin NOT on TV
Please enter pin from tv: 9220
Got pin: '9220'

AES key: d46ecd26a032ded4a2f9f4e8b7ef41f1
Traceback (most recent call last):
  File "smartcrypto.py", line 126, in <module>
    output = HelloExchange(tvPIN)
  File "smartcrypto.py", line 55, in HelloExchange
    hello_output = crypto.generateServerHello(UserId,pin)
  File "/srv/homeassistant/lib/python3.5/site-packages/PySmartCrypto/crypto.py", line 39, in generateServerHello
    cipher = AES.new(aes_key, AES.MODE_CBC, iv)
  File "/srv/homeassistant/lib/python3.5/site-packages/Crypto/Cipher/AES.py", line 206, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/Crypto/Cipher/_mode_cbc.py", line 253, in _create_cbc_cipher
    return CbcMode(cipher_state, iv)
  File "/srv/homeassistant/lib/python3.5/site-packages/Crypto/Cipher/_mode_cbc.py", line 96, in __init__
    c_uint8_ptr(iv),
  File "/srv/homeassistant/lib/python3.5/site-packages/Crypto/Util/_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
```

**Comment by eclair4151** [comment]
Try changing line 39 in crypto.py to

cipher = AES.new(aes_key, AES.MODE_CBC, iv.encode(“utf-8”))

Or to

cipher = AES.new(aes_key.encode(“utf-8”), AES.MODE_CBC, iv.encode(“utf-8”))

**Comment by luca-angemi** [comment]
Thanks. 

Before your reply I tried to change both line 38 and 72 in crypto.py to

iv = b"\x00" * BLOCK_SIZE

and it worked.

If I could ask a further question: is there a way to reuse the handshake, instead of pairing again?

**Comment by eclair4151** [comment]
Yes, i should really document everything in the read me. You just need to save the ctx and session_id from pairing. from then on you can call the same send command method and pass those values from before

**Comment by luca-angemi** [comment]
Many thanks. That worked. I guess everytime I restart the code I have just to increse the session_id, right?

**Comment by eclair4151** [comment]
im not sure. in my experience you dont need to increment it, but you can try that if you are having issues.
