### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by lebhacker** [eclair4151/SmartCrypto#6]
Traceback (most recent call last):
  File "smartcrypto.py", line 126, in <module>
    output = HelloExchange(tvPIN)
  File "smartcrypto.py", line 68, in HelloExchange
    return crypto.parseClientHello(clientHello, hello_output['hash'], hello_output['AES_key'], UserId)
  File "/home/lebhack/SmartCrypto-master/PySmartCrypto/crypto.py", line 79, in parseClientHello
    secret = bytes.fromhex(hex(pow(bnPGx, bnPrivateKey, bnPrime)).rstrip("L").lstrip("0x"))
ValueError: non-hexadecimal number found in fromhex() arg at position 255

i got:
pEncWBGx: "redacted"
pEncGx: "redacted"
pGx: "redacted"
cant get the CTX code

**Comment by eclair4151** [comment]
What model is your tv?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lebhacker** [comment]
it is UA32H4303

**Comment by eclair4151** [comment]
Hmm not sure. Unfortunately i dont really have any way to reproduce. I wish i could be of more help :/ 
But with this type of stuff if 1 byte is off anywhere in the chain the whole thing fails and finding where things go wrong is very tricky to do in person let alone across github. You could start by seeing what is inside the bytes variable since thats where the error is coming from. Bytes should be a hex number but the script says its not, so i would debug through the program if you can and see why bytes is getting a non hex value

**Comment by lebhacker** [comment]
OK later on this day i will share all the output for the script maybe we can find out where is the problem

**Comment by lebhacker** [comment]
user@laptop:~/SmartCrypto-master/PySmartCrypto$ python3 smartcrypto.py
Current state: stopped
Pin NOT on TV
Please enter pin from tv: 0000
Got pin: '0000'

AES key: 39dfa55283318d31afe5a3ff4a0e3253
AES encrypted: 2848a4f315e28f062ea77eb749bfc26f1a5b03a39b50bbbff3e4eeb5354d86b191ad03018695522f448a1eb19be0f442d1fbb8cb54057c2c0dde3f569e23e67d858416f41915ad981cd83ac7a4072bca78b5ef860377b6773cb8e6fc52650dace543cad09634c0127933cc8159775dafbfb3af903948f22fc672095a4034cba5
AES swapped: 85c7d00b9ce7172c4f92590c84f993cddea075a79e28dfc2457f343d754e9030fde03ad32d82336e27483bdddd0fd358d310ce868aea34df5b078c6907938f4c97ecec45337ed4259dc2c093875c3e8d4a34a95c607f05a6fe87173aaeb6ae58975129104334a53b3f7ed71f26465b16756e34cce49dc33909cb399962608584
data buffer: 0000000636353433323185C7D00B9CE7172C4F92590C84F993CDDEA075A79E28DFC2457F343D754E9030FDE03AD32D82336E27483BDDDD0FD358D310CE868AEA34DF5B078C6907938F4C97ECEC45337ED4259DC2C093875C3E8D4A34A95C607F05A6FE87173AAEB6AE58975129104334A53B3F7ED71F26465B16756E34CCE49DC33909CB399962608584
hash: cc9a833d87b585102b84408c4be5b95a8a0392ab
secondStepResponse: {"auth_data":"{\"auth_type\":\"SPC\",\"request_id\":\"0\",\"GeneratorClientHello\":\"010100000000000000009E00000006363534333231D8750D9023B376A2DD35B19F44F501F6D7D9A54484E46FB7D2F066E73EF0024E4545A38AAD72D6C1E29ACEF3A8DB53173C158FCA1D6BE3442262907DFF362556858BDCD5E00C56B518F9C36C702A21D9E6BB5B121070BC4738212AB5DE2EE792935D3647A09C50F0B96234FEE432AA0B1186C19B8BE2721A23BB72C5CD9144EACBBFA08D0A88FA712EF9D9668BEB5BB3A53E5BC20000000000\"}"}


thirdLen: 138
hello: 010100000000000000009e00000006363534333231d8750d9023b376a2dd35b19f44f501f6d7d9a54484e46fb7d2f066e73ef0024e4545a38aad72d6c1e29acef3a8db53173c158fca1d6be3442262907dff362556858bdcd5e00c56b518f9c36c702a21d9e6bb5b121070bc4738212ab5de2ee792935d3647a09c50f0b96234fee432aa0b1186c19b8be2721a23bb72c5cd9144eacbbfa08d0a88fa712ef9d9668beb5bb3a53e5bc20000000000
dest: 00000006363534333231d8750d9023b376a2dd35b19f44f501f6d7d9a54484e46fb7d2f066e73ef0024e4545a38aad72d6c1e29acef3a8db53173c158fca1d6be3442262907dff362556858bdcd5e00c56b518f9c36c702a21d9e6bb5b121070bc4738212ab5de2ee792935d3647a09c50f0b96234fee432aa0b1186c19b8be2721a23bb72c5cd9144eacc9a833d87b585102b84408c4be5b95a8a0392ab
userId: 654321
pEncWBGx: d8750d9023b376a2dd35b19f44f501f6d7d9a54484e46fb7d2f066e73ef0024e4545a38aad72d6c1e29acef3a8db53173c158fca1d6be3442262907dff362556858bdcd5e00c56b518f9c36c702a21d9e6bb5b121070bc4738212ab5de2ee792935d3647a09c50f0b96234fee432aa0b1186c19b8be2721a23bb72c5cd9144ea
pEncGx: d8bcffb8c95d9023280c2f452df8635ed11224849d53c9933ae25028c6419bfffb98aa7177286c96e0ec2a678ee2b742aefe4dadd5277996618fb6f4a7cbbda1ebf2072c04ae42dce414f1618d96d27d6d8412d431aaa8b01635592c30dd7db3f7cc8dc01da1bbe49d0ad7d0f1f2347d474122ba03684461ea1158cb74739cd3
pGx: 2856f477594f20b4ff5bb3f3053b278069a57ac33b4a00d69903738c319ec69b2f77fd63fd74d21427bf783d3f9059c9a57dba79a5ac5d2a280dd61b305d2b048549a18ac6c2f67209dbde71fbfcb2e6893e6656009cf0bd73f714b2dbb2e64164c4fadea40501bf06a63752e27b59ad8f4b00afa64540c0a77d0d7dd1c43957
Traceback (most recent call last):
  File "smartcrypto.py", line 126, in <module>
    output = HelloExchange(tvPIN)
  File "smartcrypto.py", line 68, in HelloExchange
    return crypto.parseClientHello(clientHello, hello_output['hash'], hello_output['AES_key'], UserId)
  File "/home/user/SmartCrypto-master/PySmartCrypto/crypto.py", line 79, in parseClientHello
    secret = bytes.fromhex(hex(pow(bnPGx, bnPrivateKey, bnPrime)).rstrip("L").lstrip("0x"))
ValueError: non-hexadecimal number found in fromhex() arg at position 255
user@laptop:~/SmartCrypto-master/PySmartCrypto$

**Comment by eclair4151** [comment]
wait what? The pin doesn't even show up on your screen? Well there's your first problem

**Comment by lebhacker** [comment]
will try to fix it hope this is my only problem !

**Comment by chimpzilla** [comment]
> it is UA32H4303

This model doesn't support IP control as far as I know. It's only 5500 series and above. Same true of J series I believe

**Comment by Mannshoch** [comment]
Have the same error on my UE55h7
I get a pin. After entering I have.
'''
30c8ab0d03096917e4079ea2e                                  Traceback (most recent call last):                           File "smartcrypto.py", line 126, in <module>
    output = HelloExchange(tvPIN)                            File "smartcrypto.py", line 68, in HelloExchange
    return crypto.parseClientHello(clientHello, hello_output['hash'], hello_output['AES_key'], UserId)                  File "/storage/emulated/0/Download/smartcrypto-master/SmartCrypto-master/PySmartCrypto/crypto.py", line 79, in parseClientHello                                                    secret = bytes.fromhex(hex(pow(bnPGx, bnPrivateKey, bnPrime)).rstrip("L").lstrip("0x"))                           ValueError: non-hexadecimal number found in fromhex() arg at position 255
'''

**Comment by eclair4151** [comment]
Hmm, unfortunately as i stated above i have no way to test or actively maintain this lib so your sorta on your own here. Sorry :/

**Comment by Mannshoch** [comment]
Found a workaround. 
After TV prompt the Pin I have to kill the script and restart it. 

The script is working if the Pin is prompted on TV when I start the script

**Comment by AngelofromTurin** [comment]
hi model tv h6203
i tried the script but response me:
current state stoped
pin NOT on tv...

**Comment by simonwanghub** [comment]
UA78KU6900JXXZ can support?

**Comment by eclair4151** [comment]
No that is a K series tv. check out this lib
https://github.com/kdschlosser/samsungctl

**Comment by simonwanghub** [comment]
> No that is a K series tv. check out this lib
> https://github.com/kdschlosser/samsungctl
Thanks,i will have a try.

**Comment by simonwanghub** [comment]
It seem doesn't work,how can i sure my TV series? K/H/J?

**Comment by eclair4151** [comment]
You can prob open an issue on that library for assistance. not much i can do here. 
The series is the 5th letter of the serial code

UA78**K**U6900JXXZ
